version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Authenticate with Docker Hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Build Docker image
          command: docker-compose -f docker-compose.ci.yml build

      - run:
          name: Push Docker image
          command: docker-compose -f docker-compose.ci.yml push
